import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider attribute="class" defaultTheme="dark">
					<main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
						<div className="flex gap-4 items-center flex-col sm:flex-row">
							<h2 className="text-4xl font-bold">PokeDir</h2>
						</div>
						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
